/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXAMPLE_H_RPCGEN
#define _EXAMPLE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define EXAMPLEPROG 0x20000001
#define EXAMPLEPROGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINTMSG 1
extern  int * printmsg_1(char **, CLIENT *);
extern  int * printmsg_1_svc(char **, struct svc_req *);
extern int exampleprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINTMSG 1
extern  int * printmsg_1();
extern  int * printmsg_1_svc();
extern int exampleprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXAMPLE_H_RPCGEN */
