function funs = data1(frmt)

	function func1(x)
		if nargin < 1
			x = string('Anon');
		end
		disp(string('Hello ') + x);
	end

	function y = func2(x)
		y = sin(x);
	end

	function y = func3(x)
		y = cos(x);
	end

	function y = func4(filename, x, del, prec)
		if nargin < 4
			prec = 8;
			if nargin == 2
				del = ' ';
			end
		end
		dlmwrite(filename, x, 'delimiter', del, 'precision', prec);
	end

	if nargin == 0
		frmt = 1;
	end
	
	funs = {};
	funs0 = {};

	funs0 = {...
		{ @func1, string('Hello message') },...
		{ @func2, string('y = sin(x)') },...
		{ @func3, string('y = cos(x)') },...
		{ @func4, string('proccess data') },...
		{ @func3, string('y = cos(x)') },...
		{ @func3, string('y = cos(x)') },...
		{ @func3, string('y = cos(x)') },...
		{ @func3, string('y = cos(x)') }...
		};
		


	funs1 = {};

	funs1{1} = [...
		string('Hello message')...
		string('y = sin(x)')...
		string('y = cos(x)')...
		string('proccess data')...
		string('y = cos(x)')...
		string('y = cos(x)')...
		string('y = cos(x)')...
		string('y = cos(x)')...
		];

	funs1{2} = {...
		@func1,...
		@func2,...
		@func3,...
		@func4,...
		@func3,...
		@func3,...
		@func3,...
		@func3,...
		};
	
	if frmt == 1
		funs = funs1;
	end

	if frmt == 0
		funs = funs0;
	end
	
	
		
end


